<?php
return [
    'wrongCity' => \App\Commands\RecordDeliveryCity::class,
    'citySelect' => \App\Commands\RecordDeliverySettlements::class,
    'wrongSet' => \App\Commands\RecordDeliverySettlements::class,
    'thisSett' => \App\Commands\RecordDeliverySettlements::class,
    'char_done' => \App\Commands\RecordGoodChar::class,
    'unit' => \App\Commands\RecordGoodUnit::class,
    'sel_manager' => \App\Commands\RecordManager::class,
    'e_sel_manager' => \App\Commands\RecordManager::class,
    'record_info' => \App\Commands\RecordList::class,
    'good_info' => \App\Commands\GoodInfo::class,
    'record_edit_butt' => \App\Commands\RecordEdit::class,
    'record_edit_back' => \App\Commands\RecordList::class,

    'e_delivery_type' => \App\Commands\RecordDeliveryType::class,
    'e_phone' => \App\Commands\RecordPhone::class,
    'e_fio' => \App\Commands\RecordName::class,
    'e_payed_status' => \App\Commands\RecordPayedStatus::class,
    'e_payed_sum' => \App\Commands\RecordPayedStatus::class,
    'e_delivery_address' => \App\Commands\RecordAddress::class,
    'e_city' => \App\Commands\RecordDeliveryCity::class,
    'e_post' => \App\Commands\RecordDeliverySettlements::class,
    'e_manager' => \App\Commands\RecordManager::class,
    'e_comment' => \App\Commands\RecordComment::class,
    'e_delivery_date' => \App\Commands\RecordDeliveryDate::class,
    'e_record_status' => \App\Commands\RecordStatus::class,
    'rstatus' => \App\Commands\RecordStatus::class,
];